if(EXISTS "C:/Users/taski/source/repos/yakuperoglu/ce103-midterm-yakup-eroglu-hasan-basri-taskin/build_win/src/tests/yachtsystem/yachtsystem_tests[1]_tests.cmake")
  include("C:/Users/taski/source/repos/yakuperoglu/ce103-midterm-yakup-eroglu-hasan-basri-taskin/build_win/src/tests/yachtsystem/yachtsystem_tests[1]_tests.cmake")
else()
  add_test(yachtsystem_tests_NOT_BUILT yachtsystem_tests_NOT_BUILT)
endif()
